services:
  dynview:
    container_name: dynview
    # build: ./viewer/sim_runner
    image: micamaca44/dynview:latest
    environment:
      - SIMULATOR_DURATION=10 # u minutama
    ports:
      - "2222:2222"
      - "8080:8080"
      - "8765:8765"
  stacker:
    container_name: stacker
    # build: ./viewer/gp_runner
    image: micamaca44/stacker:latest
    environment:
      - MODE=HEURISTIC # HEURISTIC / GENETIC
      - FEAT_SELECT=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
    volumes:
      - ./viewer/data:/data:z