services:
  dynview:
    image: micamaca44/dynview:latest
    ports:
      - "2222:2222"  # ZMQ port
      - "8765:8765"  # HTTP/WebSocket port
    environment:
      - ASPNETCORE_URLS=http://+:8765,http://+:2222